# Generated by Django 5.2.3 on 2026-07-30 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_name_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='kitchen_mode',
            field=models.CharField(choices=[('printer', 'Termal printer (KOT)'), ('tablet', 'Planşet KDS'), ('both', 'Hər ikisi')], default='both', help_text='Mətbəxə göndərmə: printer, planşet və ya hər ikisi', max_length=20),
        ),
        migrations.CreateModel(
            name='KitchenPrinter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField(default=9100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Mətbəx printeri',
                'verbose_name_plural': 'Mətbəx printerləri',
                'ordering': ['name'],
                'unique_together': {('restaurant', 'name')},
            },
        ),
    ]
