# Generated by Django 5.2.3 on 2026-07-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_kitchen_mode_kitchenprinter'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='accept_card',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='accept_cash',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='accept_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='currency',
            field=models.CharField(choices=[('AZN', 'AZN (₼)'), ('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('TRY', 'TRY (₺)')], default='AZN', max_length=8),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='customer_menu_multilang',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_fee_amount',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=8),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_fee_type',
            field=models.CharField(choices=[('fixed', 'Sabit haqq'), ('distance', 'Məsafəyə görə')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_radius_km',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_logos/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='notify_expiry_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='notify_kitchen_sound',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='notify_push_courier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='notify_push_waiter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_hours',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='panel_language',
            field=models.CharField(choices=[('az', 'Azərbaycanca'), ('ru', 'Русский'), ('en', 'English')], default='az', max_length=5),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='payment_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='payment_gateway',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='qr_design',
            field=models.CharField(choices=[('simple', 'Sadə QR'), ('branded', 'Loqolu / çərçivəli')], default='branded', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='qr_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='qr_menu_base_url',
            field=models.CharField(default='https://menu.domain.az', help_text='Müştəri menyusu bazası (slash olmadan)', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='qr_scan_mode',
            field=models.CharField(choices=[('menu_first', 'Əvvəl menyu, sonra sifariş'), ('order_direct', 'Birbaşa sifariş rejimi')], default='menu_first', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='service_charge_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='service_charge_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='kitchen_mode',
            field=models.CharField(choices=[('printer', 'Termal printer (KOT)'), ('tablet', 'Planşet KDS'), ('both', 'Hər ikisi')], default='both', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
