# Generated by Django 5.2.3 on 2026-07-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_accept_card_restaurant_accept_cash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='notify_daily_summary_hour',
            field=models.PositiveSmallIntegerField(default=23, help_text='Gündəlik xülasə saatı (0–23)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='notify_push_manager',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='notify_sound_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='notify_sound_waiter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='notify_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Kritik stok həddi (ədəd)'),
        ),
    ]
