# Generated by Django 5.2.3 on 2026-07-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_notify_daily_summary_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='device_setup_code',
            field=models.CharField(blank=True, default='', help_text='Planşeti restoran hesabına bağlamaq üçün kod', max_length=16),
        ),
    ]
