# Generated by Django 5.2.3 on 2026-07-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_device_setup_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_base_fee',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Baza haqq (məsafə tipində)', max_digits=8),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_per_km_fee',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Hər km üçün haqq', max_digits=8),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.FloatField(blank=True, help_text='Restoran koordinatı (Mapbox)', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lng',
            field=models.FloatField(blank=True, help_text='Restoran koordinatı (Mapbox)', null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_fee_amount',
            field=models.DecimalField(decimal_places=2, default=3, help_text='Sabit haqq (fee_type=fixed)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_radius_km',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Max çatdırılma radiusu (km)', max_digits=6),
        ),
    ]
