# Generated by Django 5.2.3 on 2026-08-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_qr_lan_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='custom_domain',
            field=models.CharField(
                blank=True,
                help_text='Öz domen: thedoner.az (www olmadan)',
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='storefront_enabled',
            field=models.BooleanField(
                default=True,
                help_text='Öz domen / slug ilə onlayn sifariş saytı açıqdır',
            ),
        ),
    ]
