# Generated by Django 5.2.3 on 2026-07-30 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_printjob'),
        ('restaurants', '0004_restaurant_accept_card_restaurant_accept_cash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='AZN', max_length=8)),
                ('method', models.CharField(choices=[('cash', 'Nağd'), ('card_pos', 'POS kart'), ('online', 'Onlayn (QR/link)')], default='online', max_length=20)),
                ('gateway', models.CharField(blank=True, choices=[('', '—'), ('mock', 'Mock (dev)'), ('payriff', 'Payriff'), ('epoint', 'Epoint')], default='mock', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Gözləyir'), ('processing', 'Emal olunur'), ('paid', 'Ödənilib'), ('failed', 'Uğursuz'), ('expired', 'Vaxtı bitib'), ('cancelled', 'Ləğv edilib'), ('refunded', 'Geri qaytarılıb')], default='pending', max_length=20)),
                ('payment_url', models.URLField(blank=True, default='')),
                ('qr_code_url', models.URLField(blank=True, default='')),
                ('gateway_invoice_id', models.CharField(blank=True, default='', max_length=120)),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='Idempotentlik: eyni webhook təkrar emal olunmasın', max_length=120, null=True, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Ödəniş',
                'verbose_name_plural': 'Ödənişlər',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='payments_pa_status_04c3f6_idx'), models.Index(fields=['order', 'status'], name='payments_pa_order_i_a76289_idx')],
            },
        ),
    ]
