# Generated by Django 5.2.3 on 2026-07-30 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_cancelled_at_order_cancelled_note_and_more'),
        ('restaurants', '0006_restaurant_device_setup_code'),
        ('staff', '0004_staffuser_can_cancel_preparing_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('is_available', models.BooleanField(default=False)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to='restaurants.restaurant')),
                ('staff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_profile', to='staff.staffuser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kuryer',
                'verbose_name_plural': 'Kuryerlər',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='delivery.courier')),
            ],
            options={
                'verbose_name': 'Kuryer ödənişi',
                'verbose_name_plural': 'Kuryer ödənişləri',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('offered', 'Təklif edildi'), ('accepted', 'Qəbul edildi'), ('picked_up', 'Götürüldü'), ('delivered', 'Çatdırıldı'), ('expired', 'Vaxtı bitdi'), ('cancelled', 'Ləğv')], default='offered', max_length=20)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pickup_address', models.CharField(blank=True, default='', max_length=255)),
                ('pickup_lat', models.FloatField(blank=True, null=True)),
                ('pickup_lng', models.FloatField(blank=True, null=True)),
                ('dropoff_address', models.CharField(blank=True, default='', max_length=255)),
                ('dropoff_lat', models.FloatField(blank=True, null=True)),
                ('dropoff_lng', models.FloatField(blank=True, null=True)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=30)),
                ('customer_name', models.CharField(blank=True, default='', max_length=120)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('eta_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('offer_expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_method', models.CharField(choices=[('otp', 'OTP kod'), ('photo', 'Foto')], default='otp', max_length=10)),
                ('confirmation_otp', models.CharField(blank=True, default='', max_length=4)),
                ('confirmation_photo', models.ImageField(blank=True, null=True, upload_to='delivery_proofs/')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='delivery.courier')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Çatdırılma tapşırığı',
                'verbose_name_plural': 'Çatdırılma tapşırıqları',
                'ordering': ['-offered_at'],
                'indexes': [models.Index(fields=['restaurant', 'status'], name='delivery_de_restaur_18288f_idx'), models.Index(fields=['courier', 'status'], name='delivery_de_courier_95d6dd_idx')],
            },
        ),
    ]
