# Generated by Django 5.2.3 on 2026-07-30 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Sahib'), ('manager', 'Menecer'), ('waiter', 'Ofisiant'), ('kitchen', 'Mətbəx'), ('cashier', 'Kassir'), ('courier', 'Kuryer'), ('warehouse', 'Anbar')], max_length=20)),
                ('pin_code', models.CharField(max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='restaurants.restaurant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İşçi',
                'verbose_name_plural': 'İşçilər',
            },
        ),
    ]
