# Generated by Django 5.2.3 on 2026-07-30 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='can_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='can_edit_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
