# Generated by Django 5.2.3 on 2026-07-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staffuser_pin_code_device_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='can_cancel_preparing_order',
            field=models.BooleanField(default=False, help_text='Hazırlanan sifarişi ləğv edə bilər (əks halda menecer)'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='can_discount',
            field=models.BooleanField(default=False, help_text='Endirim tətbiq edə bilər (rol defaultundan əlavə)'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='can_edit_menu',
            field=models.BooleanField(default=False, help_text='Menyu/qiymət redaktə (rol defaultundan əlavə)'),
        ),
    ]
