# Generated by Django 5.2.3 on 2026-07-30 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='capacity',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='table',
            name='height',
            field=models.FloatField(default=12),
        ),
        migrations.AddField(
            model_name='table',
            name='pos_x',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='table',
            name='pos_y',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='table',
            name='rotation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='shape',
            field=models.CharField(choices=[('round', 'Dairəvi'), ('rect', 'Düzbucaqlı')], default='round', max_length=20),
        ),
        migrations.AddField(
            model_name='table',
            name='width',
            field=models.FloatField(default=12),
        ),
        migrations.CreateModel(
            name='FloorElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('cashier', 'Kassa'), ('entry', 'Giriş'), ('exit', 'Çıxış'), ('stairs', 'Pilləkən'), ('restroom', 'Tualet'), ('wash', 'Əl yuma'), ('room', 'Otaq'), ('label', 'Yazı')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('pos_x', models.FloatField(default=10)),
                ('pos_y', models.FloatField(default=10)),
                ('width', models.FloatField(default=12)),
                ('height', models.FloatField(default=8)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_elements', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Plan elementi',
                'verbose_name_plural': 'Plan elementləri',
            },
        ),
    ]
