# Generated by Django 5.2.3 on 2026-07-30 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('tables', '0002_table_capacity_table_height_table_pos_x_table_pos_y_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='awaiting_bill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='needs_cleaning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='table',
            name='split_bill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='zone',
            field=models.CharField(choices=[('zal', 'Zal'), ('terras', 'Terras'), ('vip', 'VIP otaq')], default='zal', max_length=20),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=120)),
                ('party_size', models.PositiveIntegerField(default=2)),
                ('reserved_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Gözləyir'), ('seated', 'Oturub'), ('cancelled', 'Ləğv'), ('completed', 'Tamamlanıb')], default='pending', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurants.restaurant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tables.table')),
            ],
            options={
                'verbose_name': 'Rezervasiya',
                'verbose_name_plural': 'Rezervasiyalar',
                'ordering': ['reserved_for'],
            },
        ),
    ]
