# Generated by Django 5.2.3 on 2026-07-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_table_awaiting_bill_table_needs_cleaning_table_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='qr_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
