# Generated by Django 5.2.3 on 2026-07-30 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem_image_url'),
        ('restaurants', '0003_restaurant_kitchen_mode_kitchenprinter'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='printer',
            field=models.ForeignKey(blank=True, help_text='Bu kateqoriyanın KOT ticket-ləri hansı printerə gedir', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='restaurants.kitchenprinter'),
        ),
    ]
