# Generated by Django 5.2.3 on 2026-07-30 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_printjob'),
        ('restaurants', '0004_restaurant_accept_card_restaurant_accept_cash_and_more'),
        ('staff', '0002_staffuser_can_discount_staffuser_can_edit_menu_and_more'),
        ('tables', '0004_table_qr_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_reason',
            field=models.CharField(blank=True, choices=[('', '—'), ('customer', 'Müştəri ləğv etdi'), ('stock', 'Stok yoxdur'), ('kitchen', 'Mətbəx bacarmadı'), ('error', 'Xəta / yanlış sifariş'), ('timeout', 'Vaxt bitdi'), ('other', 'Digər')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='preparing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='served_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_orders', to='staff.staffuser'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', 'created_at'], name='orders_orde_restaur_763bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', 'status'], name='orders_orde_restaur_17016b_idx'),
        ),
    ]
