# Generated by Django 5.2.3 on 2026-07-30 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_cancelled_at_order_cancelled_note_and_more'),
        ('restaurants', '0005_restaurant_notify_daily_summary_hour_and_more'),
        ('staff', '0002_staffuser_can_discount_staffuser_can_edit_menu_and_more'),
        ('tables', '0004_table_qr_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_role', models.CharField(choices=[('waiter', 'Ofisiant'), ('kitchen', 'Mətbəx'), ('manager', 'Menecer'), ('courier', 'Kuryer'), ('all', 'Hamı')], default='manager', max_length=20)),
                ('type', models.CharField(choices=[('order_ready', 'Sifariş hazırdır'), ('waiter_call', 'Ofisiant çağırışı'), ('bill_request', 'Hesab istəyi'), ('new_order', 'Yeni sifariş'), ('new_qr_order', 'Yeni QR sifarişi'), ('order_cancelled', 'Sifariş ləğv edildi'), ('low_stock', 'Stok azalıb'), ('expiry_warning', 'Son istifadə tarixi'), ('payment_failed', 'Ödəniş uğursuz'), ('daily_summary', 'Gündəlik xülasə'), ('cancel_spike', 'Qeyri-adi ləğv sayı')], max_length=30)),
                ('priority', models.CharField(choices=[('critical', 'Kritik'), ('medium', 'Orta'), ('low', 'Aşağı')], default='medium', max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, default='', max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='staff.staffuser')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order')),
                ('related_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tables.table')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', 'is_read', '-created_at'], name='notificatio_restaur_f71b90_idx'), models.Index(fields=['restaurant', 'priority', '-created_at'], name='notificatio_restaur_38cd28_idx')],
            },
        ),
    ]
